version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    tty: true
  tests:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    tty: true
    command: ["npm", "run", "test"]    